### ISSUE TITLE
old ibridge and post-me community update and migration guides

### ISSUE THREAD

**Issue by franleplant** [alesgenova/post-me#23]
Make sure that we

- deprecate old repos in favor of this one 
- deprecate post-me npm package in favor of this one
- provide links from those old places into this one
- perhaps migrate issues from the old repos to this one
- create migration guides from old ibridge and post-me into new ibridge

**Comment by alesgenova** [comment]
On the `post-me` side the only thing that is left to do is to deprecate the published npm package (I'll do it as soon as we publish the first release post merge).
All other items were done automatically when I transferred the ownership of the github repo to the new organization.
