### ISSUE TITLE
high level apis

### ISSUE THREAD

**Issue by franleplant** [alesgenova/post-me#24]
Lib consumers (we have some feedback in old ibridge repo) value that we provide high level apis that abstract
iframe creation / hidding etc. Make sure we also include that high level functionality on this new ibridge,
it should be pretty simple to implement on top of the core that we have been designing, i.e.

```typescript
import ibridge from 'ibridge'

const remoteOrigin = SOME_URL
// resolves when the iframe triggers onLoad
const remoteWindow = await ibridge.spawnIframe(remoteOrigin)

const iparent = new ibrdige.Parent(WindowMessenger(window, remoteWindow, remoteOrigin), model)
```

we could even allow for more abstraction

```typescript
const remoteOrigin = SOME_URL
const windowMessenger = await ibridge.Messenger.spawnIframe(window, remoteOrigin)

const iparent = new ibridge.Parent(windowMessenger, model)
```

**Comment by alesgenova** [comment]
Sounds good to me, it can make the user's life slightly easier.
I like the first approach slightly better, if I had to pick.
And maybe name the method `crateIframe()`?
