### ISSUE TITLE
jsdoc on every public method

### ISSUE THREAD

**Issue by franleplant** [alesgenova/post-me#28]
jsdoc is a great tool for providing inline documentation and combining it with typescript information, additionally
with a tool such as typedoc (which is far far from perfect and far far from i.e. rust doc) we can generate automatic API documentation and even host it in github pages.

Additionally most modern IDE understand both typescript, type declarations and jsdoc comments so they will provide useful autocomplete information off of it.

- document all public methods and interfaces
- do not use jsdoc type annotations since we already have typescript
- run some tests with typedoc

**Comment by alesgenova** [comment]
Yes, it sounds great to me!
I don't have previous experience with jsdoc and typedoc, so you might be the better person to take a stab at it
