### ISSUE TITLE
WorkerMessenger `worker` parameter should accept an argument of type DedicatedWorkerGlobalScope

### ISSUE THREAD

**Issue by birtles** [alesgenova/post-me#57]
**Describe the bug**
The `self` object in a dedicated worker has type `DedicatedWorkerGlobalScope`. However, the `WorkerMessenger` constructor expects the `worker` parameter to be of type `Worker`.

It seems like that argument could be simply a union type allowing `Worker` or `DediatedWorkerGlobalScope`.

I'm happy to make up a PR for this, but I want to be sure you agree it's a bug first.

**To Reproduce**
1. Use a worker file `declare const self: DedicatedWorkerGlobalScope`.
2. Try to add `new WorkerMessenger({ worker: self })`

**Expected behavior**
No type errors.

**Actual behavior**
Typescript complains that `self` doesn't have the `terminate` method which is required for it to satisfy the definition of `Worker`.

**Comment by alesgenova** [comment]
You are absolutely right, and that's how it used to be up until [this change](https://github.com/alesgenova/post-me/commit/940206015e07b450db2add186e08fdaae05c9d93#diff-7c2cf4fe5ec69494ec9bb815c2b806de1c6c85c03b9542bc94ab4c850813fc24L68)

The reason why I changed it, was that having the union type `Worker | DediatedWorkerGlobalScope` was giving compilation problems when consuming the library in a separate project. I started looking into it, but soon gave up when it seemed like there were some conflicts between the types declaration from various versions of typescript and tslib (I don't remember exactly).

In the end I decided that having to do `new WorkerMessenger({ worker: self as any })` was a lesser evil than a compilation error in code not accessible by the user.

I will be more than happy to accept a PR to fix this issue, but I just want to make sure that we get to the bottom of why `DediatedWorkerGlobalScope` was a problematic type to begin with.

**Comment by birtles** [comment]
Oh, interesting. Thanks for the quick response.

I wonder if the issues previously encountered were because `DedicatedWorkerGlobalScope` is only defined when TypeScript is configured to include the "webworker" lib.

If that's the case (and I haven't checked), perhaps it would be best to define a local `WorkerLike` interface that just duplicates the methods that post-me needs (`postMessage` and `addMessageListener`?). That way users could pass in a `Worker` or `DedicatedWorkerGlobalScope` and it should work regardless of whether or not the project is built with the "webworker" lib enabled?

**Comment by alesgenova** [comment]
I used to have `webworker` added to the tsconfig of post-me, but maybe not to the config of the consumer. But I wouldn't like the idea of having the user need to change their tsconfig file just to use post-me.

I think defining some sort of `WorkerLite` is a very good idea. Since the `Messenger` only uses a couple of methods, the definition of the `WorkerLite` might end up being the same as the `Postable` interface that is defined in `messenger.ts`.

Gotta go to bed now, I'm open to ideas/PR :)
